<?php
require 'header.php';
master_admin_required();
$db = db_load();
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $editId = trim(post('edit_id'));
    $profileType = post($editId !== '' ? 'edit_profile_type' : 'profile_type') === 'doctor' ? 'doctor' : 'subadmin';
    $value = static fn(string $key, $default = '') => post($editId !== '' ? 'edit_' . $key : $key, $default);
    $username = trim($value('username'));
    $password = $value('password');
    if ($profileType === 'subadmin' && ($username === '' || $password === '')) {
        redirect('manage-users.php');
    }
    if ($profileType === 'doctor' || ($username !== '' && $password !== '')) {
        if (!isset($db['admins']) || !is_array($db['admins'])) $db['admins'] = [];
        $permissions = [
            'view' => !empty($_POST[$editId !== '' ? 'edit_perm_view' : 'perm_view']),
            'edit' => !empty($_POST[$editId !== '' ? 'edit_perm_edit' : 'perm_edit']),
            'delete' => !empty($_POST[$editId !== '' ? 'edit_perm_delete' : 'perm_delete'])
        ];
        $record = ['username' => $profileType === 'subadmin' ? $username : '', 'password' => $profileType === 'subadmin' ? password_hash($password, PASSWORD_DEFAULT) : '', 'role' => $profileType, 'profile_type' => $profileType, 'name' => trim($value('name')), 'gender' => $value('gender'), 'photo' => upload_image('photo'), 'dob' => $value('dob'), 'designation' => trim($value('designation')), 'mobile' => trim($value('mobile')), 'degree' => trim($value('degree')), 'email' => trim($value('email')), 'address' => trim($value('address')), 'is_doctor' => $profileType === 'doctor' || !empty($_POST[$editId !== '' ? 'edit_is_doctor' : 'is_doctor']), 'show_on_home' => !empty($_POST[$editId !== '' ? 'edit_show_on_home' : 'show_on_home']), 'permissions' => $profileType === 'subadmin' ? $permissions : ['view' => false, 'edit' => false, 'delete' => false]];
        if ($editId !== '') {
            foreach ($db['admins'] as &$admin) {
                if ((string)($admin['id'] ?? '') !== $editId) continue;
                if ($profileType === 'subadmin' && $password === '') $record['password'] = $admin['password'] ?? '';
                if ($record['photo'] === '') $record['photo'] = $admin['photo'] ?? '';
                foreach (['gender', 'dob', 'email', 'address'] as $preservedField) {
                    if (!array_key_exists('edit_' . $preservedField, $_POST)) $record[$preservedField] = $admin[$preservedField] ?? '';
                }
                $record['id'] = $admin['id'];
                $record['created_at'] = $admin['created_at'] ?? now_iso();
                $record['updated_at'] = now_iso();
                $admin = array_merge($admin, $record);
                break;
            }
            unset($admin);
        } else {
            $record['id'] = make_id();
            $record['created_at'] = now_iso();
            $db['admins'][] = $record;
        }
        db_save($db);
    }
    redirect('manage-users.php');
}
?>
<div class="admin-top"><h1>Admin Users</h1><div><button type="button" class="btn" id="openUserModal">+ Add Sub Admin</button> <button type="button" class="btn btn-light" id="openEditUserModal">Edit Profile</button></div></div>
<div class="table-wrap"><table><tr><th>Photo</th><th>Name</th><th>Username</th><th>Designation</th><th>Mobile</th><th>Permissions</th><th>Public Doctor</th><th>Created</th><th>Actions</th></tr><?php foreach (($db['admins'] ?? []) as $admin): $permissions = admin_permissions_for($admin); ?><tr><td><?php if (!empty($admin['photo'])): ?><img src="../<?= e($admin['photo']) ?>" alt="<?= e($admin['name'] ?? $admin['username'] ?? '') ?>" class="admin-user-avatar"><?php else: ?>-<?php endif; ?></td><td><?= e($admin['name'] ?? '-') ?></td><td><?= e($admin['username'] ?? '') ?></td><td><?= e($admin['designation'] ?? '-') ?></td><td><?= e($admin['mobile'] ?? '-') ?></td><td><?= e(($permissions['view'] ? 'View' : '') . ($permissions['edit'] ? ($permissions['view'] ? ', ' : '') . 'Edit' : '') . ($permissions['delete'] ? (($permissions['view'] || $permissions['edit']) ? ', ' : '') . 'Delete' : '')) ?: 'None' ?></td><td><?= !empty($admin['is_doctor']) ? 'Yes' . (!empty($admin['show_on_home']) ? ' / Home' : '') : 'No' ?></td><td><?= e($admin['created_at'] ?? '-') ?></td><td><a class="btn btn-sm btn-outline" href="admin-user-view.php?id=<?= e((string)($admin['id'] ?? '')) ?>" title="View admin details" aria-label="View <?= e($admin['username'] ?? 'admin') ?> details">&#128065;</a> <a class="btn btn-sm btn-light" href="admin-user-edit.php?id=<?= e((string)($admin['id'] ?? '')) ?>" title="Edit admin details">Edit</a></td></tr><?php endforeach; ?></table></div>
<div class="blog-modal" id="userModal" aria-hidden="true"><div class="blog-modal-dialog" role="dialog" aria-modal="true" aria-labelledby="userModalTitle"><div class="blog-modal-header"><h2 id="userModalTitle">Add Sub Admin / Staff</h2><button type="button" class="blog-modal-close" id="closeUserModal" aria-label="Close">&times;</button></div><form method="post" enctype="multipart/form-data"><div class="form-grid"><div class="field"><label>Login Username</label><input name="username" required autocomplete="off"></div><div class="field"><label>Login Password</label><div class="password-toggle-wrap"><input type="password" id="newAdminPassword" name="password" required minlength="6" autocomplete="new-password"><button type="button" class="password-toggle-btn" data-target="newAdminPassword" aria-label="Show password">👁</button></div></div><div class="field"><label>Full Name</label><input name="name" required></div><div class="field"><label>Gender</label><div class="gender-options"><label><input type="radio" name="gender" value="Male" required> Male</label><label><input type="radio" name="gender" value="Female"> Female</label><label><input type="radio" name="gender" value="Other"> Other</label></div></div><div class="field"><label>Photo</label><input type="file" name="photo" accept="image/jpeg,image/png,image/webp,image/gif"></div><div class="field"><label>DOB (Optional)</label><input type="date" name="dob"></div><div class="field"><label>Designation</label><input name="designation" required placeholder="e.g. Homeopathic Doctor"></div><div class="field"><label>Mobile Number</label><input name="mobile" required inputmode="tel"></div><div class="field"><label>Degree</label><input name="degree" required></div><div class="field"><label>Email (Optional)</label><input type="email" name="email"></div><div class="field full"><label>Address (Optional)</label><textarea name="address" rows="3"></textarea></div><div class="field full"><label>Profile Visibility</label><div class="gender-options"><label><input type="checkbox" name="is_doctor"> Show as doctor on About page</label><label><input type="checkbox" name="show_on_home"> Show doctor on main page</label></div></div><div class="field full"><label>Access Rights</label><div class="gender-options"><label><input type="checkbox" name="perm_view" checked> View</label><label><input type="checkbox" name="perm_edit" checked> Edit</label><label><input type="checkbox" name="perm_delete" checked> Delete</label></div></div><div class="field full"><button class="btn" type="submit">Create Sub Admin</button></div></div></form></div></div>
<div class="blog-modal" id="editUserModal" aria-hidden="true"><div class="blog-modal-dialog" role="dialog" aria-modal="true" aria-labelledby="editUserModalTitle"><div class="blog-modal-header"><h2 id="editUserModalTitle">Edit Profile</h2><button type="button" class="blog-modal-close" id="closeEditUserModal" aria-label="Close">&times;</button></div><form method="post" enctype="multipart/form-data"><input type="hidden" name="edit_id" id="editAdminId"><div class="form-grid"><div class="field full"><label>Profile Type</label><div class="gender-options"><label><input type="radio" name="edit_profile_type" value="subadmin" checked> Sub Admin</label><label><input type="radio" name="edit_profile_type" value="doctor"> Doctor Profile</label></div></div><div class="field"><label>Login Username</label><input name="edit_username" id="editAdminUsername"></div><div class="field"><label>New Password (Optional)</label><input type="password" name="edit_password"></div><div class="field"><label>Full Name</label><input name="edit_name" id="editAdminName" required></div><div class="field"><label>Designation</label><input name="edit_designation" id="editAdminDesignation" required></div><div class="field"><label>Mobile Number</label><input name="edit_mobile" id="editAdminMobile" required></div><div class="field"><label>Degree</label><input name="edit_degree" id="editAdminDegree" required></div><div class="field full"><label>Profile Visibility</label><div class="gender-options"><label><input type="checkbox" name="edit_is_doctor" id="editIsDoctor"> Show as doctor on About page</label><label><input type="checkbox" name="edit_show_on_home" id="editShowOnHome"> Show doctor on main page</label></div></div><div class="field full"><label>Access Rights</label><div class="gender-options"><label><input type="checkbox" name="edit_perm_view" id="editPermView"> View</label><label><input type="checkbox" name="edit_perm_edit" id="editPermEdit"> Edit</label><label><input type="checkbox" name="edit_perm_delete" id="editPermDelete"> Delete</label></div></div><div class="field full"><button class="btn" type="submit">Save Changes</button></div></div></form></div></div>
<div class="blog-modal" id="editUserModal" aria-hidden="true"><div class="blog-modal-dialog" role="dialog" aria-modal="true" aria-labelledby="editUserModalTitle"><div class="blog-modal-header"><h2 id="editUserModalTitle">Edit Profile</h2><button type="button" class="blog-modal-close" id="closeEditUserModal" aria-label="Close">&times;</button></div><form method="post" enctype="multipart/form-data"><input type="hidden" name="edit_id" id="editAdminId"><div class="form-grid"><div class="field full"><label>Profile Type</label><div class="gender-options"><label><input type="radio" name="edit_profile_type" value="subadmin" checked> Sub Admin</label><label><input type="radio" name="edit_profile_type" value="doctor"> Doctor Profile</label></div></div><div class="field"><label>Login Username</label><input name="edit_username" id="editAdminUsername"></div><div class="field"><label>New Password (Optional)</label><input type="password" name="edit_password"></div><div class="field"><label>Full Name</label><input name="edit_name" id="editAdminName" required></div><div class="field"><label>Designation</label><input name="edit_designation" id="editAdminDesignation" required></div><div class="field"><label>Mobile Number</label><input name="edit_mobile" id="editAdminMobile" required></div><div class="field"><label>Degree</label><input name="edit_degree" id="editAdminDegree" required></div><div class="field full"><label>Profile Visibility</label><div class="gender-options"><label><input type="checkbox" name="edit_is_doctor" id="editIsDoctor"> Show as doctor on About page</label><label><input type="checkbox" name="edit_show_on_home" id="editShowOnHome"> Show doctor on main page</label></div></div><div class="field full"><label>Access Rights</label><div class="gender-options"><label><input type="checkbox" name="edit_perm_view" id="editPermView"> View</label><label><input type="checkbox" name="edit_perm_edit" id="editPermEdit"> Edit</label><label><input type="checkbox" name="edit_perm_delete" id="editPermDelete"> Delete</label></div></div><div class="field full"><button class="btn" type="submit">Save Changes</button></div></div></form></div></div>
<style>
    .password-toggle-wrap { position: relative; }
    .password-toggle-wrap input { width: 100%; padding-right: 42px; }
    .password-toggle-btn {
        position: absolute;
        right: 10px;
        top: 50%;
        transform: translateY(-50%);
        border: 0;
        background: transparent;
        cursor: pointer;
        font-size: 18px;
        line-height: 1;
        color: #555;
        padding: 4px 6px;
    }
</style>
<script>(function(){const form=document.querySelector('#userModal form');if(!form)return;const grid=form.querySelector('.form-grid');const typeField=document.createElement('div');typeField.className='field full profile-type-field';typeField.innerHTML='<label>Profile Type</label><div class="gender-options"><label><input type="radio" name="profile_type" value="subadmin" checked> Sub Admin</label><label><input type="radio" name="profile_type" value="doctor"> Doctor Profile</label></div>';grid.prepend(typeField);const username=form.querySelector('[name="username"]');const password=form.querySelector('[name="password"]');const doctor=form.querySelector('[name="is_doctor"]');form.querySelectorAll('[name="profile_type"]').forEach(function(radio){radio.addEventListener('change',function(){const isDoctor=this.value==='doctor';username.required=!isDoctor;password.required=!isDoctor;username.disabled=isDoctor;password.disabled=isDoctor;if(isDoctor){username.value='';password.value='';if(doctor)doctor.checked=true;}});});})();</script>
<script>(function(){const modal=document.getElementById('userModal');const close=()=>{modal.classList.remove('show');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';};document.getElementById('openUserModal').addEventListener('click',()=>{modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';});document.getElementById('closeUserModal').addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('show'))close();});document.querySelectorAll('.password-toggle-btn').forEach(function(button){button.addEventListener('click',function(){const input=document.getElementById(this.dataset.target);if(!input)return;const isPassword=input.type==='password';input.type=isPassword?'text':'password';this.textContent=isPassword?'🙈':'👁';this.setAttribute('aria-label',isPassword?'Hide password':'Show password');});});})();</script>
<script>
(function(){
    const modal=document.getElementById('editUserModal');
    const form=modal.querySelector('form');
    const profiles=<?= json_encode(array_values(array_map(function($admin){ return ['id'=>(string)($admin['id']??''),'profile_type'=>$admin['profile_type']??$admin['role']??'subadmin','username'=>$admin['username']??'','name'=>$admin['name']??'','designation'=>$admin['designation']??'','mobile'=>$admin['mobile']??'','degree'=>$admin['degree']??'','is_doctor'=>!empty($admin['is_doctor']),'show_on_home'=>!empty($admin['show_on_home']),'permissions'=>admin_permissions_for($admin)]; }, $db['admins']??[])), JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP) ?>;
    const select=document.createElement('select');select.name='profile_picker';select.className='profile-picker';select.innerHTML='<option value="">Select profile to edit</option>'+profiles.map(function(profile){return '<option value="'+profile.id+'">'+(profile.name||profile.username||'Profile')+'</option>';}).join('');
    const pickerField=document.createElement('div');pickerField.className='field full';pickerField.innerHTML='<label>Select Profile</label>';pickerField.appendChild(select);form.querySelector('.form-grid').prepend(pickerField);
    const close=function(){modal.classList.remove('show');modal.setAttribute('aria-hidden','true');};
    function syncType(){const doctor=form.querySelector('[name="edit_profile_type"]:checked').value==='doctor';form.querySelector('[name="edit_username"]').disabled=doctor;form.querySelector('[name="edit_username"]').required=!doctor;form.querySelector('[name="edit_password"]').disabled=doctor;form.querySelector('[name="edit_is_doctor"]').checked=doctor||form.querySelector('[name="edit_is_doctor"]').checked;}
    select.addEventListener('change',function(){const profile=profiles.find(function(item){return item.id===select.value;});if(!profile)return;form.querySelector('[name="edit_id"]').value=profile.id;form.querySelector('[name="edit_username"]').value=profile.username;form.querySelector('[name="edit_name"]').value=profile.name;form.querySelector('[name="edit_designation"]').value=profile.designation;form.querySelector('[name="edit_mobile"]').value=profile.mobile;form.querySelector('[name="edit_degree"]').value=profile.degree;form.querySelectorAll('[name="edit_profile_type"]').forEach(function(radio){radio.checked=radio.value===profile.profile_type;});form.querySelector('[name="edit_is_doctor"]').checked=profile.is_doctor;form.querySelector('[name="edit_show_on_home"]').checked=profile.show_on_home;form.querySelector('[name="edit_perm_view"]').checked=profile.permissions.view;form.querySelector('[name="edit_perm_edit"]').checked=profile.permissions.edit;form.querySelector('[name="edit_perm_delete"]').checked=profile.permissions.delete;syncType();});
    form.querySelectorAll('[name="edit_profile_type"]').forEach(function(radio){radio.addEventListener('change',syncType);});
    function openEditor(id){select.value=id;select.dispatchEvent(new Event('change'));modal.classList.add('show');modal.setAttribute('aria-hidden','false');}
    document.getElementById('openEditUserModal').addEventListener('click',function(){modal.classList.add('show');modal.setAttribute('aria-hidden','false');});document.querySelectorAll('a[href^="admin-user-edit.php?id="]').forEach(function(link){link.addEventListener('click',function(event){event.preventDefault();openEditor(new URL(link.href).searchParams.get('id'));});});document.getElementById('closeEditUserModal').addEventListener('click',close);modal.addEventListener('click',function(event){if(event.target===modal)close();});
})();
</script>
<?php require 'footer.php'; ?>
