<?php require 'header.php'; $db=db_load(); $canEdit=current_admin_can('edit'); $canDelete=current_admin_can('delete'); $p=find_item($db['patients'],get('id')); if(!$p) redirect('patients.php'); $aps=array_values(array_filter($db['appointments'],fn($a)=>$a['patient_id']===$p['id'])); $paid=array_sum(array_map(fn($a)=>(float)($a['amount']??0),$aps)); ?><div class="admin-top"><h1><?=e($p['name'])?></h1><div class="actions"><?php if ($canEdit): ?><a class="btn btn-outline" href="patient-form.php?id=<?=e($p['id'])?>">Edit Patient</a><?php endif; ?><?php if ($canEdit): ?><a class="btn" href="appointment-edit.php?patient_id=<?=e($p['id'])?>">+ Appointment</a><?php endif; ?><button type="button" class="btn btn-outline" id="openPdfModal">Download PDF</button></div></div><div class="dash-cards"><div class="dash-card"><span>Patient No</span><strong style="font-size:20px"><?=e($p['number'])?></strong></div><div class="dash-card"><span>Total Paid</span><strong>₹<?=number_format($paid,2)?></strong></div><div class="dash-card"><span>Total Appointments</span><strong><?=count($aps)?></strong></div><div class="dash-card"><span>Mobile</span><strong style="font-size:20px"><?=e($p['mobile'])?></strong></div></div><div class="form-card"><h2>Patient Details</h2><p><b>DOB:</b> <?=e(date_fmt($p['dob']))?> &nbsp; <b>Age:</b> <?=e($p['age'])?> &nbsp; <b>Gender:</b> <?=e($p['gender'])?> &nbsp; <b>Blood:</b> <?=e($p['blood_group'])?></p><p><b>Address:</b> <?=e($p['address'])?>, <?=e($p['city'])?>, <?=e($p['state'])?>, <?=e($p['country'])?></p></div><br><div class="form-card"><h2>Appointment History</h2><div class="table-wrap"><table><tr><th>Appointment No</th><th>Date</th><th>Time</th><th>Status</th><th>Amount</th><th>Medicine</th><th>Instructions</th><th>Next Appointment</th><th>Action</th></tr><?php foreach($aps as $a): ?><tr><td><?=e($a['number'])?></td><td><?=e(date_fmt($a['date']))?></td><td><?=e($a['time'])?></td><td><span class="badge"><?=e($a['status'])?></span></td><td>₹<?=number_format((float)$a['amount'],2)?></td><td><?=e($a['medicine'])?></td><td><?=e($a['instructions'])?></td><td><?=e(date_fmt($a['next_date']))?></td><td><?php if ($canEdit): ?><a class="btn btn-sm btn-outline" href="appointment-edit.php?id=<?=e($a['id'])?>">View / Edit</a><?php else: ?>-<?php endif; ?></td></tr><?php endforeach; ?></table></div></div><div class="blog-modal" id="pdfModal" aria-hidden="true"><div class="blog-modal-dialog" role="dialog" aria-modal="true" aria-labelledby="pdfModalTitle" style="max-width:900px;">
    <div class="blog-modal-header"><h2 id="pdfModalTitle">Patient PDF Preview</h2><button type="button" class="blog-modal-close" id="closePdfModal" aria-label="Close">&times;</button></div>
    <div class="blog-modal-body" style="padding:12px 18px;">
        <iframe src="patient-pdf.php?id=<?=e($p['id'])?>" title="Patient PDF preview" style="width:100%;height:75vh;border:1px solid #dfeae3;border-radius:10px;background:#fff;"></iframe>
    </div>
</div></div>
<script>
(function(){
  const modal = document.getElementById('pdfModal');
  const openBtn = document.getElementById('openPdfModal');
  const closeBtn = document.getElementById('closePdfModal');
  const closeModal = function(){ modal.classList.remove('show'); modal.setAttribute('aria-hidden', 'true'); document.body.style.overflow = ''; };
  openBtn.addEventListener('click', function(){ modal.classList.add('show'); modal.setAttribute('aria-hidden', 'false'); document.body.style.overflow = 'hidden'; });
  closeBtn.addEventListener('click', closeModal);
  modal.addEventListener('click', function(e){ if (e.target === modal) closeModal(); });
  document.addEventListener('keydown', function(e){ if (e.key === 'Escape' && modal.classList.contains('show')) closeModal(); });
})();
</script>
<?php require 'footer.php'; ?>
